package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anime generated by hbm2java
 */
@Entity
@Table(name="anime"
    ,catalog="postgres"
)
public class Anime  implements java.io.Serializable {


     private int id;
     private Season season;
     private Source source;
     private Type type;
     private Rating rating;
     private Status status;
     private String title;
     private String titleJapanese;
     private String url;
     private String imageUrl;
     private double score;
     private Double scoredBy;
     private Date startDate;
     private Date endDate;
     private String synopsis;
     private Double rank;
     private int popularity;
     private int members;
     private int favorites;
     private Double episodes;
     private Double year;
     private int watching;
     private int completed;
     private int onHold;
     private int dropped;
     private int planToWatch;
     private int total;
     private double score1Votes;
     private double score1Percentage;
     private double score2Votes;
     private double score2Percentage;
     private double score3Votes;
     private double score3Percentage;
     private double score4Votes;
     private double score4Percentage;
     private double score5Votes;
     private double score5Percentage;
     private double score6Votes;
     private double score6Percentage;
     private double score7Votes;
     private double score7Percentage;
     private double score8Votes;
     private double score8Percentage;
     private double score9Votes;
     private double score9Percentage;
     private double score10Votes;
     private double score10Percentage;
     private Set<Genre> genres = new HashSet<Genre>(0);
     private Set<ExplicitGenre> explicitGenres = new HashSet<ExplicitGenre>(0);
     private Set<Anime> animesForRecommendedAnimeId = new HashSet<Anime>(0);
     private Set<Theme> themes = new HashSet<Theme>(0);
     private Set<PersonVoiceWork> personVoiceWorks = new HashSet<PersonVoiceWork>(0);
     private Set<Licensor> licensors = new HashSet<Licensor>(0);
     private Set<Anime> animesForAnimeId = new HashSet<Anime>(0);
     private Set<Producer> producers = new HashSet<Producer>(0);
     private Set<Studio> studios = new HashSet<Studio>(0);
     private Set<PersonAnimeWork> personAnimeWorks = new HashSet<PersonAnimeWork>(0);
     private Set<Demographic> demographics = new HashSet<Demographic>(0);
     private Set<StreamingService> streamingServices = new HashSet<StreamingService>(0);
     private Set<CharacterAnimeWork> characterAnimeWorks = new HashSet<CharacterAnimeWork>(0);

    public Anime() {
    }

	
    public Anime(int id, Source source, Status status, String title, String titleJapanese, String url, String imageUrl, double score, int popularity, int members, int favorites, int watching, int completed, int onHold, int dropped, int planToWatch, int total, double score1Votes, double score1Percentage, double score2Votes, double score2Percentage, double score3Votes, double score3Percentage, double score4Votes, double score4Percentage, double score5Votes, double score5Percentage, double score6Votes, double score6Percentage, double score7Votes, double score7Percentage, double score8Votes, double score8Percentage, double score9Votes, double score9Percentage, double score10Votes, double score10Percentage) {
        this.id = id;
        this.source = source;
        this.status = status;
        this.title = title;
        this.titleJapanese = titleJapanese;
        this.url = url;
        this.imageUrl = imageUrl;
        this.score = score;
        this.popularity = popularity;
        this.members = members;
        this.favorites = favorites;
        this.watching = watching;
        this.completed = completed;
        this.onHold = onHold;
        this.dropped = dropped;
        this.planToWatch = planToWatch;
        this.total = total;
        this.score1Votes = score1Votes;
        this.score1Percentage = score1Percentage;
        this.score2Votes = score2Votes;
        this.score2Percentage = score2Percentage;
        this.score3Votes = score3Votes;
        this.score3Percentage = score3Percentage;
        this.score4Votes = score4Votes;
        this.score4Percentage = score4Percentage;
        this.score5Votes = score5Votes;
        this.score5Percentage = score5Percentage;
        this.score6Votes = score6Votes;
        this.score6Percentage = score6Percentage;
        this.score7Votes = score7Votes;
        this.score7Percentage = score7Percentage;
        this.score8Votes = score8Votes;
        this.score8Percentage = score8Percentage;
        this.score9Votes = score9Votes;
        this.score9Percentage = score9Percentage;
        this.score10Votes = score10Votes;
        this.score10Percentage = score10Percentage;
    }
    public Anime(int id, Season season, Source source, Type type, Rating rating, Status status, String title, String titleJapanese, String url, String imageUrl, double score, Double scoredBy, Date startDate, Date endDate, String synopsis, Double rank, int popularity, int members, int favorites, Double episodes, Double year, int watching, int completed, int onHold, int dropped, int planToWatch, int total, double score1Votes, double score1Percentage, double score2Votes, double score2Percentage, double score3Votes, double score3Percentage, double score4Votes, double score4Percentage, double score5Votes, double score5Percentage, double score6Votes, double score6Percentage, double score7Votes, double score7Percentage, double score8Votes, double score8Percentage, double score9Votes, double score9Percentage, double score10Votes, double score10Percentage, Set<Genre> genres, Set<ExplicitGenre> explicitGenres, Set<Anime> animesForRecommendedAnimeId, Set<Theme> themes, Set<PersonVoiceWork> personVoiceWorks, Set<Licensor> licensors, Set<Anime> animesForAnimeId, Set<Producer> producers, Set<Studio> studios, Set<PersonAnimeWork> personAnimeWorks, Set<Demographic> demographics, Set<StreamingService> streamingServices, Set<CharacterAnimeWork> characterAnimeWorks) {
       this.id = id;
       this.season = season;
       this.source = source;
       this.type = type;
       this.rating = rating;
       this.status = status;
       this.title = title;
       this.titleJapanese = titleJapanese;
       this.url = url;
       this.imageUrl = imageUrl;
       this.score = score;
       this.scoredBy = scoredBy;
       this.startDate = startDate;
       this.endDate = endDate;
       this.synopsis = synopsis;
       this.rank = rank;
       this.popularity = popularity;
       this.members = members;
       this.favorites = favorites;
       this.episodes = episodes;
       this.year = year;
       this.watching = watching;
       this.completed = completed;
       this.onHold = onHold;
       this.dropped = dropped;
       this.planToWatch = planToWatch;
       this.total = total;
       this.score1Votes = score1Votes;
       this.score1Percentage = score1Percentage;
       this.score2Votes = score2Votes;
       this.score2Percentage = score2Percentage;
       this.score3Votes = score3Votes;
       this.score3Percentage = score3Percentage;
       this.score4Votes = score4Votes;
       this.score4Percentage = score4Percentage;
       this.score5Votes = score5Votes;
       this.score5Percentage = score5Percentage;
       this.score6Votes = score6Votes;
       this.score6Percentage = score6Percentage;
       this.score7Votes = score7Votes;
       this.score7Percentage = score7Percentage;
       this.score8Votes = score8Votes;
       this.score8Percentage = score8Percentage;
       this.score9Votes = score9Votes;
       this.score9Percentage = score9Percentage;
       this.score10Votes = score10Votes;
       this.score10Percentage = score10Percentage;
       this.genres = genres;
       this.explicitGenres = explicitGenres;
       this.animesForRecommendedAnimeId = animesForRecommendedAnimeId;
       this.themes = themes;
       this.personVoiceWorks = personVoiceWorks;
       this.licensors = licensors;
       this.animesForAnimeId = animesForAnimeId;
       this.producers = producers;
       this.studios = studios;
       this.personAnimeWorks = personAnimeWorks;
       this.demographics = demographics;
       this.streamingServices = streamingServices;
       this.characterAnimeWorks = characterAnimeWorks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="season_id")
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="source_id", nullable=false)
    public Source getSource() {
        return this.source;
    }
    
    public void setSource(Source source) {
        this.source = source;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id")
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rating_id")
    public Rating getRating() {
        return this.rating;
    }
    
    public void setRating(Rating rating) {
        this.rating = rating;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="title", nullable=false, length=512)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="title_japanese", nullable=false, length=512)
    public String getTitleJapanese() {
        return this.titleJapanese;
    }
    
    public void setTitleJapanese(String titleJapanese) {
        this.titleJapanese = titleJapanese;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="image_url", nullable=false)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="score", nullable=false, precision=17)
    public double getScore() {
        return this.score;
    }
    
    public void setScore(double score) {
        this.score = score;
    }

    
    @Column(name="scored_by", precision=17)
    public Double getScoredBy() {
        return this.scoredBy;
    }
    
    public void setScoredBy(Double scoredBy) {
        this.scoredBy = scoredBy;
    }

    @Column(name="start_date", length=13)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Column(name="end_date", length=13)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="synopsis", length=5000)
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    
    @Column(name="rank", precision=17)
    public Double getRank() {
        return this.rank;
    }
    
    public void setRank(Double rank) {
        this.rank = rank;
    }

    
    @Column(name="popularity", nullable=false)
    public int getPopularity() {
        return this.popularity;
    }
    
    public void setPopularity(int popularity) {
        this.popularity = popularity;
    }

    
    @Column(name="members", nullable=false)
    public int getMembers() {
        return this.members;
    }
    
    public void setMembers(int members) {
        this.members = members;
    }

    
    @Column(name="favorites", nullable=false)
    public int getFavorites() {
        return this.favorites;
    }
    
    public void setFavorites(int favorites) {
        this.favorites = favorites;
    }

    
    @Column(name="episodes", precision=17)
    public Double getEpisodes() {
        return this.episodes;
    }
    
    public void setEpisodes(Double episodes) {
        this.episodes = episodes;
    }

    
    @Column(name="year", precision=17)
    public Double getYear() {
        return this.year;
    }
    
    public void setYear(Double year) {
        this.year = year;
    }

    
    @Column(name="watching", nullable=false)
    public int getWatching() {
        return this.watching;
    }
    
    public void setWatching(int watching) {
        this.watching = watching;
    }

    
    @Column(name="completed", nullable=false)
    public int getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(int completed) {
        this.completed = completed;
    }

    
    @Column(name="on_hold", nullable=false)
    public int getOnHold() {
        return this.onHold;
    }
    
    public void setOnHold(int onHold) {
        this.onHold = onHold;
    }

    
    @Column(name="dropped", nullable=false)
    public int getDropped() {
        return this.dropped;
    }
    
    public void setDropped(int dropped) {
        this.dropped = dropped;
    }

    
    @Column(name="plan_to_watch", nullable=false)
    public int getPlanToWatch() {
        return this.planToWatch;
    }
    
    public void setPlanToWatch(int planToWatch) {
        this.planToWatch = planToWatch;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

    
    @Column(name="score_1_votes", nullable=false, precision=17)
    public double getScore1Votes() {
        return this.score1Votes;
    }
    
    public void setScore1Votes(double score1Votes) {
        this.score1Votes = score1Votes;
    }

    
    @Column(name="score_1_percentage", nullable=false, precision=17)
    public double getScore1Percentage() {
        return this.score1Percentage;
    }
    
    public void setScore1Percentage(double score1Percentage) {
        this.score1Percentage = score1Percentage;
    }

    
    @Column(name="score_2_votes", nullable=false, precision=17)
    public double getScore2Votes() {
        return this.score2Votes;
    }
    
    public void setScore2Votes(double score2Votes) {
        this.score2Votes = score2Votes;
    }

    
    @Column(name="score_2_percentage", nullable=false, precision=17)
    public double getScore2Percentage() {
        return this.score2Percentage;
    }
    
    public void setScore2Percentage(double score2Percentage) {
        this.score2Percentage = score2Percentage;
    }

    
    @Column(name="score_3_votes", nullable=false, precision=17)
    public double getScore3Votes() {
        return this.score3Votes;
    }
    
    public void setScore3Votes(double score3Votes) {
        this.score3Votes = score3Votes;
    }

    
    @Column(name="score_3_percentage", nullable=false, precision=17)
    public double getScore3Percentage() {
        return this.score3Percentage;
    }
    
    public void setScore3Percentage(double score3Percentage) {
        this.score3Percentage = score3Percentage;
    }

    
    @Column(name="score_4_votes", nullable=false, precision=17)
    public double getScore4Votes() {
        return this.score4Votes;
    }
    
    public void setScore4Votes(double score4Votes) {
        this.score4Votes = score4Votes;
    }

    
    @Column(name="score_4_percentage", nullable=false, precision=17)
    public double getScore4Percentage() {
        return this.score4Percentage;
    }
    
    public void setScore4Percentage(double score4Percentage) {
        this.score4Percentage = score4Percentage;
    }

    
    @Column(name="score_5_votes", nullable=false, precision=17)
    public double getScore5Votes() {
        return this.score5Votes;
    }
    
    public void setScore5Votes(double score5Votes) {
        this.score5Votes = score5Votes;
    }

    
    @Column(name="score_5_percentage", nullable=false, precision=17)
    public double getScore5Percentage() {
        return this.score5Percentage;
    }
    
    public void setScore5Percentage(double score5Percentage) {
        this.score5Percentage = score5Percentage;
    }

    
    @Column(name="score_6_votes", nullable=false, precision=17)
    public double getScore6Votes() {
        return this.score6Votes;
    }
    
    public void setScore6Votes(double score6Votes) {
        this.score6Votes = score6Votes;
    }

    
    @Column(name="score_6_percentage", nullable=false, precision=17)
    public double getScore6Percentage() {
        return this.score6Percentage;
    }
    
    public void setScore6Percentage(double score6Percentage) {
        this.score6Percentage = score6Percentage;
    }

    
    @Column(name="score_7_votes", nullable=false, precision=17)
    public double getScore7Votes() {
        return this.score7Votes;
    }
    
    public void setScore7Votes(double score7Votes) {
        this.score7Votes = score7Votes;
    }

    
    @Column(name="score_7_percentage", nullable=false, precision=17)
    public double getScore7Percentage() {
        return this.score7Percentage;
    }
    
    public void setScore7Percentage(double score7Percentage) {
        this.score7Percentage = score7Percentage;
    }

    
    @Column(name="score_8_votes", nullable=false, precision=17)
    public double getScore8Votes() {
        return this.score8Votes;
    }
    
    public void setScore8Votes(double score8Votes) {
        this.score8Votes = score8Votes;
    }

    
    @Column(name="score_8_percentage", nullable=false, precision=17)
    public double getScore8Percentage() {
        return this.score8Percentage;
    }
    
    public void setScore8Percentage(double score8Percentage) {
        this.score8Percentage = score8Percentage;
    }

    
    @Column(name="score_9_votes", nullable=false, precision=17)
    public double getScore9Votes() {
        return this.score9Votes;
    }
    
    public void setScore9Votes(double score9Votes) {
        this.score9Votes = score9Votes;
    }

    
    @Column(name="score_9_percentage", nullable=false, precision=17)
    public double getScore9Percentage() {
        return this.score9Percentage;
    }
    
    public void setScore9Percentage(double score9Percentage) {
        this.score9Percentage = score9Percentage;
    }

    
    @Column(name="score_10_votes", nullable=false, precision=17)
    public double getScore10Votes() {
        return this.score10Votes;
    }
    
    public void setScore10Votes(double score10Votes) {
        this.score10Votes = score10Votes;
    }

    
    @Column(name="score_10_percentage", nullable=false, precision=17)
    public double getScore10Percentage() {
        return this.score10Percentage;
    }
    
    public void setScore10Percentage(double score10Percentage) {
        this.score10Percentage = score10Percentage;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_genre", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="genre_id", nullable=false) })
    public Set<Genre> getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set<Genre> genres) {
        this.genres = genres;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_explicit_genre", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="explicit_genre_id", nullable=false) })
    public Set<ExplicitGenre> getExplicitGenres() {
        return this.explicitGenres;
    }
    
    public void setExplicitGenres(Set<ExplicitGenre> explicitGenres) {
        this.explicitGenres = explicitGenres;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_recommendation", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="recommended_anime_id", nullable=false) })
    public Set<Anime> getAnimesForRecommendedAnimeId() {
        return this.animesForRecommendedAnimeId;
    }
    
    public void setAnimesForRecommendedAnimeId(Set<Anime> animesForRecommendedAnimeId) {
        this.animesForRecommendedAnimeId = animesForRecommendedAnimeId;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_theme", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="theme_id", nullable=false) })
    public Set<Theme> getThemes() {
        return this.themes;
    }
    
    public void setThemes(Set<Theme> themes) {
        this.themes = themes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anime")
    public Set<PersonVoiceWork> getPersonVoiceWorks() {
        return this.personVoiceWorks;
    }
    
    public void setPersonVoiceWorks(Set<PersonVoiceWork> personVoiceWorks) {
        this.personVoiceWorks = personVoiceWorks;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_licensor", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="licensor_id", nullable=false) })
    public Set<Licensor> getLicensors() {
        return this.licensors;
    }
    
    public void setLicensors(Set<Licensor> licensors) {
        this.licensors = licensors;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_recommendation", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="recommended_anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) })
    public Set<Anime> getAnimesForAnimeId() {
        return this.animesForAnimeId;
    }
    
    public void setAnimesForAnimeId(Set<Anime> animesForAnimeId) {
        this.animesForAnimeId = animesForAnimeId;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_producer", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="producer_id", nullable=false) })
    public Set<Producer> getProducers() {
        return this.producers;
    }
    
    public void setProducers(Set<Producer> producers) {
        this.producers = producers;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_studio", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="studio_id", nullable=false) })
    public Set<Studio> getStudios() {
        return this.studios;
    }
    
    public void setStudios(Set<Studio> studios) {
        this.studios = studios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anime")
    public Set<PersonAnimeWork> getPersonAnimeWorks() {
        return this.personAnimeWorks;
    }
    
    public void setPersonAnimeWorks(Set<PersonAnimeWork> personAnimeWorks) {
        this.personAnimeWorks = personAnimeWorks;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_demographic", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="demographic_id", nullable=false) })
    public Set<Demographic> getDemographics() {
        return this.demographics;
    }
    
    public void setDemographics(Set<Demographic> demographics) {
        this.demographics = demographics;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="anime_streaming_service", schema="public", catalog="postgres", joinColumns = { 
        @JoinColumn(name="anime_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="streaming_service_id", nullable=false) })
    public Set<StreamingService> getStreamingServices() {
        return this.streamingServices;
    }
    
    public void setStreamingServices(Set<StreamingService> streamingServices) {
        this.streamingServices = streamingServices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="anime")
    public Set<CharacterAnimeWork> getCharacterAnimeWorks() {
        return this.characterAnimeWorks;
    }
    
    public void setCharacterAnimeWorks(Set<CharacterAnimeWork> characterAnimeWorks) {
        this.characterAnimeWorks = characterAnimeWorks;
    }




}


