package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Date;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name="app_user"
    ,catalog="postgres"
)
public class AppUser  implements java.io.Serializable {


     private int id;
     private Gender gender;
     private Country country;
     private Date birthday;
     private Date joinedDate;
     private String username;

    public AppUser() {
    }

	
    public AppUser(int id, Country country, Date joinedDate, String username) {
        this.id = id;
        this.country = country;
        this.joinedDate = joinedDate;
        this.username = username;
    }
    public AppUser(int id, Gender gender, Country country, Date birthday, Date joinedDate, String username) {
       this.id = id;
       this.gender = gender;
       this.country = country;
       this.birthday = birthday;
       this.joinedDate = joinedDate;
       this.username = username;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gender_id")
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    @Column(name="birthday", length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Column(name="joined_date", nullable=false, length=13)
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }

    
    @Column(name="username", nullable=false, length=255)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


