package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CharacterNicknameId generated by hbm2java
 */
@Embeddable
public class CharacterNicknameId  implements java.io.Serializable {


     private int characterId;
     private String nickname;

    public CharacterNicknameId() {
    }

    public CharacterNicknameId(int characterId, String nickname) {
       this.characterId = characterId;
       this.nickname = nickname;
    }
   


    @Column(name="character_id", nullable=false)
    public int getCharacterId() {
        return this.characterId;
    }
    
    public void setCharacterId(int characterId) {
        this.characterId = characterId;
    }


    @Column(name="nickname", nullable=false, length=255)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CharacterNicknameId) ) return false;
		 CharacterNicknameId castOther = ( CharacterNicknameId ) other; 
         
		 return (this.getCharacterId()==castOther.getCharacterId())
 && ( (this.getNickname()==castOther.getNickname()) || ( this.getNickname()!=null && castOther.getNickname()!=null && this.getNickname().equals(castOther.getNickname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getCharacterId();
        result = 37 * result + ( getNickname() == null ? 0 : this.getNickname().hashCode() );
         return result;
   }   


}


