package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * CharacterRole generated by hbm2java
 */
@Entity
@Table(name="character_role"
    ,catalog="postgres"
)
public class CharacterRole  implements java.io.Serializable {


     private int id;
     private String role;
     private Set<CharacterAnimeWork> characterAnimeWorks = new HashSet<CharacterAnimeWork>(0);

    public CharacterRole() {
    }

	
    public CharacterRole(int id, String role) {
        this.id = id;
        this.role = role;
    }
    public CharacterRole(int id, String role, Set<CharacterAnimeWork> characterAnimeWorks) {
       this.id = id;
       this.role = role;
       this.characterAnimeWorks = characterAnimeWorks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="role", nullable=false, length=64)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="characterRole")
    public Set<CharacterAnimeWork> getCharacterAnimeWorks() {
        return this.characterAnimeWorks;
    }
    
    public void setCharacterAnimeWorks(Set<CharacterAnimeWork> characterAnimeWorks) {
        this.characterAnimeWorks = characterAnimeWorks;
    }




}


