package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CharacterAnimeWork generated by hbm2java
 */
@Entity
@Table(name="character_anime_work"
    ,catalog="postgres"
)
public class CharacterAnimeWork  implements java.io.Serializable {


     private CharacterAnimeWorkId id;
     private Character character;
     private CharacterRole characterRole;
     private Anime anime;

    public CharacterAnimeWork() {
    }

    public CharacterAnimeWork(CharacterAnimeWorkId id, Character character, CharacterRole characterRole, Anime anime) {
       this.id = id;
       this.character = character;
       this.characterRole = characterRole;
       this.anime = anime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="animeId", column=@Column(name="anime_id", nullable=false) ), 
        @AttributeOverride(name="characterId", column=@Column(name="character_id", nullable=false) ) } )
    public CharacterAnimeWorkId getId() {
        return this.id;
    }
    
    public void setId(CharacterAnimeWorkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="character_id", nullable=false, insertable=false, updatable=false)
    public Character getCharacter() {
        return this.character;
    }
    
    public void setCharacter(Character character) {
        this.character = character;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="character_role_id", nullable=false)
    public CharacterRole getCharacterRole() {
        return this.characterRole;
    }
    
    public void setCharacterRole(CharacterRole characterRole) {
        this.characterRole = characterRole;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="anime_id", nullable=false, insertable=false, updatable=false)
    public Anime getAnime() {
        return this.anime;
    }
    
    public void setAnime(Anime anime) {
        this.anime = anime;
    }




}


