package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CharacterNickname generated by hbm2java
 */
@Entity
@Table(name="character_nickname"
    ,catalog="postgres"
)
public class CharacterNickname  implements java.io.Serializable {


     private CharacterNicknameId id;
     private Character character;

    public CharacterNickname() {
    }

    public CharacterNickname(CharacterNicknameId id, Character character) {
       this.id = id;
       this.character = character;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="characterId", column=@Column(name="character_id", nullable=false) ), 
        @AttributeOverride(name="nickname", column=@Column(name="nickname", nullable=false, length=255) ) } )
    public CharacterNicknameId getId() {
        return this.id;
    }
    
    public void setId(CharacterNicknameId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="character_id", nullable=false, insertable=false, updatable=false)
    public Character getCharacter() {
        return this.character;
    }
    
    public void setCharacter(Character character) {
        this.character = character;
    }




}


