package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Character generated by hbm2java
 */
@Entity
@Table(name="character"
    ,catalog="postgres"
)
public class Character  implements java.io.Serializable {


     private int id;
     private String url;
     private String name;
     private String nameJapanese;
     private String imageUrl;
     private int favorites;
     private String about;
     private Set<PersonVoiceWork> personVoiceWorks = new HashSet<PersonVoiceWork>(0);
     private Set<CharacterNickname> characterNicknames = new HashSet<CharacterNickname>(0);
     private Set<CharacterAnimeWork> characterAnimeWorks = new HashSet<CharacterAnimeWork>(0);

    public Character() {
    }

	
    public Character(int id, String url, String name, String imageUrl, int favorites) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.imageUrl = imageUrl;
        this.favorites = favorites;
    }
    public Character(int id, String url, String name, String nameJapanese, String imageUrl, int favorites, String about, Set<PersonVoiceWork> personVoiceWorks, Set<CharacterNickname> characterNicknames, Set<CharacterAnimeWork> characterAnimeWorks) {
       this.id = id;
       this.url = url;
       this.name = name;
       this.nameJapanese = nameJapanese;
       this.imageUrl = imageUrl;
       this.favorites = favorites;
       this.about = about;
       this.personVoiceWorks = personVoiceWorks;
       this.characterNicknames = characterNicknames;
       this.characterAnimeWorks = characterAnimeWorks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="name_japanese", length=255)
    public String getNameJapanese() {
        return this.nameJapanese;
    }
    
    public void setNameJapanese(String nameJapanese) {
        this.nameJapanese = nameJapanese;
    }

    
    @Column(name="image_url", nullable=false)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="favorites", nullable=false)
    public int getFavorites() {
        return this.favorites;
    }
    
    public void setFavorites(int favorites) {
        this.favorites = favorites;
    }

    
    @Column(name="about", length=16383)
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="character")
    public Set<PersonVoiceWork> getPersonVoiceWorks() {
        return this.personVoiceWorks;
    }
    
    public void setPersonVoiceWorks(Set<PersonVoiceWork> personVoiceWorks) {
        this.personVoiceWorks = personVoiceWorks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="character")
    public Set<CharacterNickname> getCharacterNicknames() {
        return this.characterNicknames;
    }
    
    public void setCharacterNicknames(Set<CharacterNickname> characterNicknames) {
        this.characterNicknames = characterNicknames;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="character")
    public Set<CharacterAnimeWork> getCharacterAnimeWorks() {
        return this.characterAnimeWorks;
    }
    
    public void setCharacterAnimeWorks(Set<CharacterAnimeWork> characterAnimeWorks) {
        this.characterAnimeWorks = characterAnimeWorks;
    }




}


