package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CharacterAnimeWorkId generated by hbm2java
 */
@Embeddable
public class CharacterAnimeWorkId  implements java.io.Serializable {


     private int animeId;
     private int characterId;

    public CharacterAnimeWorkId() {
    }

    public CharacterAnimeWorkId(int animeId, int characterId) {
       this.animeId = animeId;
       this.characterId = characterId;
    }
   


    @Column(name="anime_id", nullable=false)
    public int getAnimeId() {
        return this.animeId;
    }
    
    public void setAnimeId(int animeId) {
        this.animeId = animeId;
    }


    @Column(name="character_id", nullable=false)
    public int getCharacterId() {
        return this.characterId;
    }
    
    public void setCharacterId(int characterId) {
        this.characterId = characterId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CharacterAnimeWorkId) ) return false;
		 CharacterAnimeWorkId castOther = ( CharacterAnimeWorkId ) other; 
         
		 return (this.getAnimeId()==castOther.getAnimeId())
 && (this.getCharacterId()==castOther.getCharacterId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getAnimeId();
        result = 37 * result + this.getCharacterId();
         return result;
   }   


}


