package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="postgres"
)
public class Country  implements java.io.Serializable {


     private int id;
     private String country;
     private Set<AppUser> appUsers = new HashSet<AppUser>(0);
     private Set<Person> persons = new HashSet<Person>(0);

    public Country() {
    }

	
    public Country(int id, String country) {
        this.id = id;
        this.country = country;
    }
    public Country(int id, String country, Set<AppUser> appUsers, Set<Person> persons) {
       this.id = id;
       this.country = country;
       this.appUsers = appUsers;
       this.persons = persons;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="country", nullable=false, length=128)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<AppUser> getAppUsers() {
        return this.appUsers;
    }
    
    public void setAppUsers(Set<AppUser> appUsers) {
        this.appUsers = appUsers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


