package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Demographic generated by hbm2java
 */
@Entity
@Table(name="demographic"
    ,catalog="postgres"
)
public class Demographic  implements java.io.Serializable {


     private int id;
     private String demographic;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Demographic() {
    }

	
    public Demographic(int id, String demographic) {
        this.id = id;
        this.demographic = demographic;
    }
    public Demographic(int id, String demographic, Set<Anime> animes) {
       this.id = id;
       this.demographic = demographic;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="demographic", nullable=false, length=128)
    public String getDemographic() {
        return this.demographic;
    }
    
    public void setDemographic(String demographic) {
        this.demographic = demographic;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="demographics")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


