package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * ExplicitGenre generated by hbm2java
 */
@Entity
@Table(name="explicit_genre"
    ,catalog="postgres"
)
public class ExplicitGenre  implements java.io.Serializable {


     private int id;
     private String explicitGenre;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public ExplicitGenre() {
    }

	
    public ExplicitGenre(int id, String explicitGenre) {
        this.id = id;
        this.explicitGenre = explicitGenre;
    }
    public ExplicitGenre(int id, String explicitGenre, Set<Anime> animes) {
       this.id = id;
       this.explicitGenre = explicitGenre;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="explicit_genre", nullable=false, length=128)
    public String getExplicitGenre() {
        return this.explicitGenre;
    }
    
    public void setExplicitGenre(String explicitGenre) {
        this.explicitGenre = explicitGenre;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="explicitGenres")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


