package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name="gender"
    ,catalog="postgres"
)
public class Gender  implements java.io.Serializable {


     private int id;
     private String gender;
     private Set<AppUser> appUsers = new HashSet<AppUser>(0);

    public Gender() {
    }

	
    public Gender(int id, String gender) {
        this.id = id;
        this.gender = gender;
    }
    public Gender(int id, String gender, Set<AppUser> appUsers) {
       this.id = id;
       this.gender = gender;
       this.appUsers = appUsers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="gender", nullable=false, length=64)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gender")
    public Set<AppUser> getAppUsers() {
        return this.appUsers;
    }
    
    public void setAppUsers(Set<AppUser> appUsers) {
        this.appUsers = appUsers;
    }




}


