package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="genre"
    ,catalog="postgres"
)
public class Genre  implements java.io.Serializable {


     private int id;
     private String genre;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Genre() {
    }

	
    public Genre(int id, String genre) {
        this.id = id;
        this.genre = genre;
    }
    public Genre(int id, String genre, Set<Anime> animes) {
       this.id = id;
       this.genre = genre;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="genre", nullable=false, length=128)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="genres")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


