package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name="language"
    ,catalog="postgres"
)
public class Language  implements java.io.Serializable {


     private int id;
     private String language;
     private Set<PersonVoiceWork> personVoiceWorks = new HashSet<PersonVoiceWork>(0);

    public Language() {
    }

	
    public Language(int id, String language) {
        this.id = id;
        this.language = language;
    }
    public Language(int id, String language, Set<PersonVoiceWork> personVoiceWorks) {
       this.id = id;
       this.language = language;
       this.personVoiceWorks = personVoiceWorks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="language", nullable=false, length=64)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="language")
    public Set<PersonVoiceWork> getPersonVoiceWorks() {
        return this.personVoiceWorks;
    }
    
    public void setPersonVoiceWorks(Set<PersonVoiceWork> personVoiceWorks) {
        this.personVoiceWorks = personVoiceWorks;
    }




}


