package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Licensor generated by hbm2java
 */
@Entity
@Table(name="licensor"
    ,catalog="postgres"
)
public class Licensor  implements java.io.Serializable {


     private int id;
     private String licensor;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Licensor() {
    }

	
    public Licensor(int id, String licensor) {
        this.id = id;
        this.licensor = licensor;
    }
    public Licensor(int id, String licensor, Set<Anime> animes) {
       this.id = id;
       this.licensor = licensor;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="licensor", nullable=false, length=255)
    public String getLicensor() {
        return this.licensor;
    }
    
    public void setLicensor(String licensor) {
        this.licensor = licensor;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="licensors")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


