package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PersonAnimeWork generated by hbm2java
 */
@Entity
@Table(name="person_anime_work"
    ,catalog="postgres"
)
public class PersonAnimeWork  implements java.io.Serializable {


     private PersonAnimeWorkId id;
     private Person person;
     private Anime anime;
     private String position;

    public PersonAnimeWork() {
    }

    public PersonAnimeWork(PersonAnimeWorkId id, Person person, Anime anime, String position) {
       this.id = id;
       this.person = person;
       this.anime = anime;
       this.position = position;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="animeId", column=@Column(name="anime_id", nullable=false) ), 
        @AttributeOverride(name="personId", column=@Column(name="person_id", nullable=false) ) } )
    public PersonAnimeWorkId getId() {
        return this.id;
    }
    
    public void setId(PersonAnimeWorkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false, insertable=false, updatable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="anime_id", nullable=false, insertable=false, updatable=false)
    public Anime getAnime() {
        return this.anime;
    }
    
    public void setAnime(Anime anime) {
        this.anime = anime;
    }

    
    @Column(name="position", nullable=false, length=1024)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


