package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PersonVoiceWork generated by hbm2java
 */
@Entity
@Table(name="person_voice_work"
    ,catalog="postgres"
)
public class PersonVoiceWork  implements java.io.Serializable {


     private PersonVoiceWorkId id;
     private Language language;
     private Character character;
     private Person person;
     private Anime anime;

    public PersonVoiceWork() {
    }

    public PersonVoiceWork(PersonVoiceWorkId id, Language language, Character character, Person person, Anime anime) {
       this.id = id;
       this.language = language;
       this.character = character;
       this.person = person;
       this.anime = anime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="animeId", column=@Column(name="anime_id", nullable=false) ), 
        @AttributeOverride(name="characterId", column=@Column(name="character_id", nullable=false) ), 
        @AttributeOverride(name="languageId", column=@Column(name="language_id", nullable=false) ), 
        @AttributeOverride(name="personId", column=@Column(name="person_id", nullable=false) ) } )
    public PersonVoiceWorkId getId() {
        return this.id;
    }
    
    public void setId(PersonVoiceWorkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="language_id", nullable=false, insertable=false, updatable=false)
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="character_id", nullable=false, insertable=false, updatable=false)
    public Character getCharacter() {
        return this.character;
    }
    
    public void setCharacter(Character character) {
        this.character = character;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false, insertable=false, updatable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="anime_id", nullable=false, insertable=false, updatable=false)
    public Anime getAnime() {
        return this.anime;
    }
    
    public void setAnime(Anime anime) {
        this.anime = anime;
    }




}


