package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="postgres"
)
public class Person  implements java.io.Serializable {


     private int id;
     private Country country;
     private String url;
     private String websiteUrl;
     private String imageUrl;
     private String name;
     private String givenName;
     private String familyName;
     private Date birthday;
     private int favorites;
     private String city;
     private Set<PersonVoiceWork> personVoiceWorks = new HashSet<PersonVoiceWork>(0);
     private Set<PersonAnimeWork> personAnimeWorks = new HashSet<PersonAnimeWork>(0);
     private Set<PersonAlternateName> personAlternateNames = new HashSet<PersonAlternateName>(0);

    public Person() {
    }

	
    public Person(int id, Country country, String url, int favorites, String city) {
        this.id = id;
        this.country = country;
        this.url = url;
        this.favorites = favorites;
        this.city = city;
    }
    public Person(int id, Country country, String url, String websiteUrl, String imageUrl, String name, String givenName, String familyName, Date birthday, int favorites, String city, Set<PersonVoiceWork> personVoiceWorks, Set<PersonAnimeWork> personAnimeWorks, Set<PersonAlternateName> personAlternateNames) {
       this.id = id;
       this.country = country;
       this.url = url;
       this.websiteUrl = websiteUrl;
       this.imageUrl = imageUrl;
       this.name = name;
       this.givenName = givenName;
       this.familyName = familyName;
       this.birthday = birthday;
       this.favorites = favorites;
       this.city = city;
       this.personVoiceWorks = personVoiceWorks;
       this.personAnimeWorks = personAnimeWorks;
       this.personAlternateNames = personAlternateNames;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="website_url")
    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    
    @Column(name="image_url")
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="name", length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="given_name", length=255)
    public String getGivenName() {
        return this.givenName;
    }
    
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    
    @Column(name="family_name", length=255)
    public String getFamilyName() {
        return this.familyName;
    }
    
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    @Column(name="birthday", length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="favorites", nullable=false)
    public int getFavorites() {
        return this.favorites;
    }
    
    public void setFavorites(int favorites) {
        this.favorites = favorites;
    }

    
    @Column(name="city", nullable=false, length=255)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<PersonVoiceWork> getPersonVoiceWorks() {
        return this.personVoiceWorks;
    }
    
    public void setPersonVoiceWorks(Set<PersonVoiceWork> personVoiceWorks) {
        this.personVoiceWorks = personVoiceWorks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<PersonAnimeWork> getPersonAnimeWorks() {
        return this.personAnimeWorks;
    }
    
    public void setPersonAnimeWorks(Set<PersonAnimeWork> personAnimeWorks) {
        this.personAnimeWorks = personAnimeWorks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<PersonAlternateName> getPersonAlternateNames() {
        return this.personAlternateNames;
    }
    
    public void setPersonAlternateNames(Set<PersonAlternateName> personAlternateNames) {
        this.personAlternateNames = personAlternateNames;
    }




}


