package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PersonAlternateName generated by hbm2java
 */
@Entity
@Table(name="person_alternate_name"
    ,catalog="postgres"
)
public class PersonAlternateName  implements java.io.Serializable {


     private PersonAlternateNameId id;
     private Person person;

    public PersonAlternateName() {
    }

    public PersonAlternateName(PersonAlternateNameId id, Person person) {
       this.id = id;
       this.person = person;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alternateName", column=@Column(name="alternate_name", nullable=false, length=255) ), 
        @AttributeOverride(name="personId", column=@Column(name="person_id", nullable=false) ) } )
    public PersonAlternateNameId getId() {
        return this.id;
    }
    
    public void setId(PersonAlternateNameId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false, insertable=false, updatable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }




}


