package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * PersonAlternateNameId generated by hbm2java
 */
@Embeddable
public class PersonAlternateNameId  implements java.io.Serializable {


     private String alternateName;
     private int personId;

    public PersonAlternateNameId() {
    }

    public PersonAlternateNameId(String alternateName, int personId) {
       this.alternateName = alternateName;
       this.personId = personId;
    }
   


    @Column(name="alternate_name", nullable=false, length=255)
    public String getAlternateName() {
        return this.alternateName;
    }
    
    public void setAlternateName(String alternateName) {
        this.alternateName = alternateName;
    }


    @Column(name="person_id", nullable=false)
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonAlternateNameId) ) return false;
		 PersonAlternateNameId castOther = ( PersonAlternateNameId ) other; 
         
		 return ( (this.getAlternateName()==castOther.getAlternateName()) || ( this.getAlternateName()!=null && castOther.getAlternateName()!=null && this.getAlternateName().equals(castOther.getAlternateName()) ) )
 && (this.getPersonId()==castOther.getPersonId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAlternateName() == null ? 0 : this.getAlternateName().hashCode() );
        result = 37 * result + this.getPersonId();
         return result;
   }   


}


