package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * PersonAnimeWorkId generated by hbm2java
 */
@Embeddable
public class PersonAnimeWorkId  implements java.io.Serializable {


     private int animeId;
     private int personId;

    public PersonAnimeWorkId() {
    }

    public PersonAnimeWorkId(int animeId, int personId) {
       this.animeId = animeId;
       this.personId = personId;
    }
   


    @Column(name="anime_id", nullable=false)
    public int getAnimeId() {
        return this.animeId;
    }
    
    public void setAnimeId(int animeId) {
        this.animeId = animeId;
    }


    @Column(name="person_id", nullable=false)
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonAnimeWorkId) ) return false;
		 PersonAnimeWorkId castOther = ( PersonAnimeWorkId ) other; 
         
		 return (this.getAnimeId()==castOther.getAnimeId())
 && (this.getPersonId()==castOther.getPersonId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getAnimeId();
        result = 37 * result + this.getPersonId();
         return result;
   }   


}


