package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * PersonVoiceWorkId generated by hbm2java
 */
@Embeddable
public class PersonVoiceWorkId  implements java.io.Serializable {


     private int animeId;
     private int characterId;
     private int languageId;
     private int personId;

    public PersonVoiceWorkId() {
    }

    public PersonVoiceWorkId(int animeId, int characterId, int languageId, int personId) {
       this.animeId = animeId;
       this.characterId = characterId;
       this.languageId = languageId;
       this.personId = personId;
    }
   


    @Column(name="anime_id", nullable=false)
    public int getAnimeId() {
        return this.animeId;
    }
    
    public void setAnimeId(int animeId) {
        this.animeId = animeId;
    }


    @Column(name="character_id", nullable=false)
    public int getCharacterId() {
        return this.characterId;
    }
    
    public void setCharacterId(int characterId) {
        this.characterId = characterId;
    }


    @Column(name="language_id", nullable=false)
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }


    @Column(name="person_id", nullable=false)
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonVoiceWorkId) ) return false;
		 PersonVoiceWorkId castOther = ( PersonVoiceWorkId ) other; 
         
		 return (this.getAnimeId()==castOther.getAnimeId())
 && (this.getCharacterId()==castOther.getCharacterId())
 && (this.getLanguageId()==castOther.getLanguageId())
 && (this.getPersonId()==castOther.getPersonId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getAnimeId();
        result = 37 * result + this.getCharacterId();
        result = 37 * result + this.getLanguageId();
        result = 37 * result + this.getPersonId();
         return result;
   }   


}


