package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Producer generated by hbm2java
 */
@Entity
@Table(name="producer"
    ,catalog="postgres"
)
public class Producer  implements java.io.Serializable {


     private int id;
     private String producer;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Producer() {
    }

	
    public Producer(int id, String producer) {
        this.id = id;
        this.producer = producer;
    }
    public Producer(int id, String producer, Set<Anime> animes) {
       this.id = id;
       this.producer = producer;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="producer", nullable=false, length=255)
    public String getProducer() {
        return this.producer;
    }
    
    public void setProducer(String producer) {
        this.producer = producer;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="producers")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


