package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name="rating"
    ,catalog="postgres"
)
public class Rating  implements java.io.Serializable {


     private int id;
     private String rating;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Rating() {
    }

	
    public Rating(int id, String rating) {
        this.id = id;
        this.rating = rating;
    }
    public Rating(int id, String rating, Set<Anime> animes) {
       this.id = id;
       this.rating = rating;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="rating", nullable=false, length=64)
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rating")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


