package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Season generated by hbm2java
 */
@Entity
@Table(name="season"
    ,catalog="postgres"
)
public class Season  implements java.io.Serializable {


     private int id;
     private String season;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Season() {
    }

	
    public Season(int id, String season) {
        this.id = id;
        this.season = season;
    }
    public Season(int id, String season, Set<Anime> animes) {
       this.id = id;
       this.season = season;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="season", nullable=false, length=32)
    public String getSeason() {
        return this.season;
    }
    
    public void setSeason(String season) {
        this.season = season;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="season")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


