package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Source generated by hbm2java
 */
@Entity
@Table(name="source"
    ,catalog="postgres"
)
public class Source  implements java.io.Serializable {


     private int id;
     private String source;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Source() {
    }

	
    public Source(int id, String source) {
        this.id = id;
        this.source = source;
    }
    public Source(int id, String source, Set<Anime> animes) {
       this.id = id;
       this.source = source;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="source", nullable=false, length=128)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="source")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


