package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="postgres"
)
public class Status  implements java.io.Serializable {


     private int id;
     private String status;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Status() {
    }

	
    public Status(int id, String status) {
        this.id = id;
        this.status = status;
    }
    public Status(int id, String status, Set<Anime> animes) {
       this.id = id;
       this.status = status;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=64)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


