package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * StreamingService generated by hbm2java
 */
@Entity
@Table(name="streaming_service"
    ,catalog="postgres"
)
public class StreamingService  implements java.io.Serializable {


     private int id;
     private String streamingService;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public StreamingService() {
    }

	
    public StreamingService(int id, String streamingService) {
        this.id = id;
        this.streamingService = streamingService;
    }
    public StreamingService(int id, String streamingService, Set<Anime> animes) {
       this.id = id;
       this.streamingService = streamingService;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="streaming_service", nullable=false, length=255)
    public String getStreamingService() {
        return this.streamingService;
    }
    
    public void setStreamingService(String streamingService) {
        this.streamingService = streamingService;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="streamingServices")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


