package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Studio generated by hbm2java
 */
@Entity
@Table(name="studio"
    ,catalog="postgres"
)
public class Studio  implements java.io.Serializable {


     private int id;
     private String studio;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Studio() {
    }

	
    public Studio(int id, String studio) {
        this.id = id;
        this.studio = studio;
    }
    public Studio(int id, String studio, Set<Anime> animes) {
       this.id = id;
       this.studio = studio;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="studio", nullable=false, length=255)
    public String getStudio() {
        return this.studio;
    }
    
    public void setStudio(String studio) {
        this.studio = studio;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="studios")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


