package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name="theme"
    ,catalog="postgres"
)
public class Theme  implements java.io.Serializable {


     private int id;
     private String theme;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Theme() {
    }

	
    public Theme(int id, String theme) {
        this.id = id;
        this.theme = theme;
    }
    public Theme(int id, String theme, Set<Anime> animes) {
       this.id = id;
       this.theme = theme;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="theme", nullable=false, length=128)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="themes")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


