package com.sqldataservice.model;
// Generated Feb 23, 2026, 9:11:47 PM by Hibernate Tools 7.2.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name="type"
    ,catalog="postgres"
)
public class Type  implements java.io.Serializable {


     private int id;
     private String type;
     private Set<Anime> animes = new HashSet<Anime>(0);

    public Type() {
    }

	
    public Type(int id, String type) {
        this.id = id;
        this.type = type;
    }
    public Type(int id, String type, Set<Anime> animes) {
       this.id = id;
       this.type = type;
       this.animes = animes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=64)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="type")
    public Set<Anime> getAnimes() {
        return this.animes;
    }
    
    public void setAnimes(Set<Anime> animes) {
        this.animes = animes;
    }




}


